### PR TITLE
Fix ESM import

### PR DESCRIPTION
**Pull request by perrin4869**
So sorry!! Native ESM import fails without the exension

### CODE REVIEW

**Comment by perrin4869** [comment]
hm... there are some severe incompatibilities between the output of the functions here and what was being output by the originals, and I'm not very well versed in the subject matter ><;;
For example, translating Russian files, some fields are being completely dropped:

```
msgid "a##apple"
msgid_plural "a##apple"
msgstr[0] "У меня есть яблоко"
msgstr[1] "У меня {count} яблока"
msgstr[2] "У меня {count} яблок"
```

turns into

```json
{
        "apple": "У меня есть яблоко",
        "apple_plural": "У меня {count} яблок",
        "apple_negative__negative": "У меня нет яблока"
}
```

where `msgstr[1]` from the source is dropped... this might be because of the differences between the plurals in this repo and in `i18next-gettext-converter`...
Any advise?

**Comment by adrai** [comment]
It might be with the new v4 format there is some issues with the multiple plural forms mapping between gettext and json... https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals

**Comment by perrin4869** [comment]
Is this the case even when not setting `compatibilityJSON: 'v4'`?

**Comment by adrai** [comment]
> Is this the case even when not setting `compatibilityJSON: 'v4'`?

in theory no...

**Comment by perrin4869** [comment]
I can try to dig into it, but I think it's a bug in this library...

**Comment by adrai** [comment]
If you have some time, this would be great

**Pull request merged**
